### PR TITLE
Update config.js for Graziella

### PR DESCRIPTION
**Pull request by fazio91**
Now you can call with /graziella and return: "grazie graziella grazie a sto cazzo"

### CODE REVIEW

**Comment by dottorblaster** [comment]
Thank you! I'll review this in a couple of days I think

**Comment by Dreeg** [comment]
Sorry but the correct form isn't "Grazie, graziella e grazie al cazzo"?

**Comment by dottorblaster** [comment]
@fazio91 do you plan to add support for `big` case?

**Comment by dottorblaster** [comment]
Closing because of unimplemented feature.

**Pull request closed without merging**
